language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t lejlathielking/docker-react -f Dockerfile.dev .

script:
  docker run -e CI=true lejlathielking/docker-react npm run test -- --coverage